name: Deploy to itch.io 😎

on: [workflow_dispatch]

env:
  ITCH_USERNAME: heimogames
  ITCH_GAME_ID: multiplayerminigame

jobs:

  deploy:
    name: Upload to Itch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        channel:
          - webgl
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          name: Build-Multiplayerminigame
          path: build/
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./build/
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
          buildNumber: ${{ needs.version.outputs.version_hash }}